{
  "artifacts": [],
  "command": "main",
  "experiment": {
    "base_dir": "/home/lgrootde/Generative-re-tests",
    "dependencies": [
      "datasets==2.17.1",
      "evaluate==0.4.1",
      "numpy==1.26.4",
      "sacred==0.8.5",
      "torch==2.2.1",
      "transformers==4.38.1",
      "wasabi==1.1.2"
    ],
    "mainfile": "run.py",
    "name": "run",
    "repositories": [
      {
        "commit": "6529e5257b4dadf60033fae6fda01e20b9f06dde",
        "dirty": true,
        "url": "https://github.com/ontox-hu/Generative-re-tests"
      }
    ],
    "sources": [
      [
        "run.py",
        "_sources/run_753cfeb012eb95fdf811c25992094b08.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/sacred/config/captured_function.py\", line 42, in captured_function\n    result = wrapped(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/home/lgrootde/Generative-re-tests/run.py\", line 547, in main\n    trainer.train()\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/transformers/trainer.py\", line 1624, in train\n    return inner_training_loop(\n           ^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/transformers/trainer.py\", line 1961, in _inner_training_loop\n    tr_loss_step = self.training_step(model, inputs)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/transformers/trainer.py\", line 2902, in training_step\n    loss = self.compute_loss(model, inputs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/transformers/trainer.py\", line 2925, in compute_loss\n    outputs = model(**inputs)\n              ^^^^^^^^^^^^^^^\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/torch/nn/modules/module.py\", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/torch/nn/modules/module.py\", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/transformers/models/t5/modeling_t5.py\", line 1748, in forward\n    decoder_outputs = self.decoder(\n                      ^^^^^^^^^^^^^\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/torch/nn/modules/module.py\", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/torch/nn/modules/module.py\", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/transformers/models/t5/modeling_t5.py\", line 1115, in forward\n    layer_outputs = layer_module(\n                    ^^^^^^^^^^^^^\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/torch/nn/modules/module.py\", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/torch/nn/modules/module.py\", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/transformers/models/t5/modeling_t5.py\", line 695, in forward\n    self_attention_outputs = self.layer[0](\n                             ^^^^^^^^^^^^^^\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/torch/nn/modules/module.py\", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/torch/nn/modules/module.py\", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/transformers/models/t5/modeling_t5.py\", line 602, in forward\n    attention_output = self.SelfAttention(\n                       ^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/torch/nn/modules/module.py\", line 1511, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/torch/nn/modules/module.py\", line 1520, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/transformers/models/t5/modeling_t5.py\", line 532, in forward\n    scores = torch.matmul(\n             ^^^^^^^^^^^^^\n",
    "torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 46.00 MiB. GPU 0 has a total capacity of 79.15 GiB of which 43.06 MiB is free. Including non-PyTorch memory, this process has 79.09 GiB memory in use. Of the allocated memory 78.53 GiB is allocated by PyTorch, and 73.68 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)\n"
  ],
  "heartbeat": "2024-04-11T15:23:14.266070",
  "host": {
    "ENV": {},
    "cpu": "AMD EPYC 7V13 64-Core Processor",
    "gpus": {
      "driver_version": "545.23.08",
      "gpus": [
        {
          "model": "NVIDIA A100 80GB PCIe",
          "persistence_mode": false,
          "total_memory": 81920
        }
      ]
    },
    "hostname": "jupyternoteboo",
    "os": [
      "Linux",
      "Linux-5.15.0-1059-azure-x86_64-with-glibc2.31"
    ],
    "python_version": "3.12.1"
  },
  "meta": {
    "command": "main",
    "config_updates": {},
    "named_configs": [],
    "options": {
      "--beat-interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--id": null,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print-config": false,
      "--priority": null,
      "--queue": false,
      "--s3": null,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [],
      "help": false,
      "with": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2024-04-11T15:22:22.529481",
  "status": "FAILED",
  "stop_time": "2024-04-11T15:23:14.811097"
}